endlessm/eos-theme

backgrounds/Makefile.am, backgrounds/endlessos-backgrounds-default.xml.in.in
This will help removing a dependency on the Endless SDK library from
some core OS components.
[endlessm/eos-shell#4831]
=> backgrounds: install default bgs per language and not per personality

settings/65gtk-overlay-scrolling, settings/Makefile.am
Based on user research, we've found that many users in our target market
are confused by thin/disappearing scroll bars.  With the new overlay
scrolling feature in GTK+, we need to explicitly disable this feature
to retain our current scrollbar theme.
[endlessm/eos-shell#5215]
=> Set env var to disable gtk overlay scrolling

debian/eos-theme.install
Used to set an environment variable to disable gtk overlay scrolling.
[endlessm/eos-shell#5215-debian]
=> Install into /etc/X11/Xsession.d

settings/com.endlessm.settings.gschema.override.in
We don't ship those any more.
[endlessm/eos-shell#5272]
=> settings: don't use eos-app- names for dash favorites

settings/com.endlessm.settings.gschema.override.in
Now that we have added pinning to the taskbar, and we are considering
removing the dash favorites feature altogether in the future, we no
longer want to encourage use of the dash for favorites.
[endlessm/eos-shell#6319]
=> Remove default dash favorites

settings/com.endlessm.settings.gschema.override.in
Tracker does not follow symlinks, so we need to explicitly specify
the absolute path.  This is necessary for the sample videos
to show up by default in the new version of totem.
[endlessm/eos-shell#5039]
=> Let tracker index Endless sample media content

debian/eos-theme.install
To match commit 19cfe4ea. Without this, the OBS build fails:
dh_install: eos-theme missing files: usr/share/gnome-background-properties
https://phabricator.endlessm.com/T11083
=> Remove gnome-background-properties from install file

settings/com.endlessm.settings.gschema.override.in
This was missed when we switched back to Nautilus.
https://phabricator.endlessm.com/T11491
=> settings: fix file manager search provider override

settings/com.endlessm.settings.gschema.override.in
This enables right-click and middle-click when clicking the touchpad (as
opposed to just tapping).
https://phabricator.endlessm.com/T11564
=> T11564: settings: Change touchpad click-method to fingers

settings/com.endlessm.settings.gschema.override.in
This reverts commit c881b7a4b5b3b834ce70584f6ac42236532982cf.
libinput provides software buttons emulation using either the number of
fingers touching the pad (also called clickfinger behavior), or the area
of the touchpad defined for left/right buttons, but not both at the same
time as the older Synaptics driver does.
The "default" value is not a libinput default (which would be the same
for all touchpads), but a device-specific default: clickfinger behavior
is only enabled on Apple touchpads, and areas on others.
To avoid confusing all users that have markings on their touchpads
defining button areas, lets revert this back to the default.
https://phabricator.endlessm.com/T11564
=> Revert "settings: Change touchpad click-method to fingers"

settings/com.endlessm.settings.gschema.override.in
Instead, just set it to the one for the C locale. Other personalities
will have their default set using a dconf override.
https://phabricator.endlessm.com/T10782
=> settings: don't use special URI for default background

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T11688
=> Override the GNOME Software settings to hide the non-free tags

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T11119
=> Do not show the sources option/dialog in GNOME Software's app menu

settings/com.endlessm.settings.gschema.override.in
We don't want this by default.
https://phabricator.endlessm.com/T11689
=> settings: disable gnome-software folder management

settings/com.endlessm.settings.gschema.override.in
eos-theme seems like a better place for this preference.
=> Move Rhythmbox override out of Rhythmbox package

settings/com.endlessm.settings.gschema.override.in
It needs to be false as we do not want our users to be performing
downloads unexpectedly.
https://phabricator.endlessm.com/T13407
=> settings: Override GNOME Software's download-updates

settings/com.endlessm.settings.gschema.override.in
The ambient light detection does not work reliably at this time,
and on some laptops (e.g., the Lenovo Yoga 900) causes the
backlight to become significantly brighter whenever attempting
to watch a video with the brightness at a minimum.
https://phabricator.endlessm.com/T15607
=> Disable automatic brightness adjustment

settings/com.endlessm.settings.gschema.override.in
Observing users going through the display settings change dialog, it
might be that the default timeout of 20 seconds is too short for
someone to read it and understand the question.
https://phabricator.endlessm.com/T16276
=> Increase display settings change timeout up to 30 seconds

settings/Makefile.am, settings/user.in
This should be merged together with changes to eos-image-builder
which stop the file being created in /etc/dconf and changes to
eos-boot-helper to remove the file from /etc on upgrade if it's
no longer needed.
https://phabricator.endlessm.com/T15704
=> add endless-specific dconf user profile to /usr/share/dconf

settings/com.endlessm.settings.gschema.override.in
settings: Enable geoclue location services by default
=> settings: Enable geoclue location services by default

settings/com.endlessm.settings.gschema.override.in
Now that we expose this feature in Endless, let's set the default
lock screen to match the default desktop background.
https://phabricator.endlessm.com/T17243
=> Specify the default lock screen image

settings/com.endlessm.settings.gschema.override.in
We found that many users were getting confused and thought
that the touchpad was broken.
https://phabricator.endlessm.com/T18022
=> settings: enable touchpad tap-to-click by default

settings/com.endlessm.settings.gschema.override.in
This was preventing HiDPI configurations from working, as a explicit scaling
factor of 1 would prevent the OS to automatically pick the right one.
https://phabricator.endlessm.com/T18349
=> Don't force a scaling factor, to automatically select that the right one

po/POTFILES.skip
Intltool can't deal with automake 1.15's decision to use a 2 level build directory for `distcheck`. Work around it like everyone else.
https://bugs.launchpad.net/intltool/+bug/1117944
https://phabricator.endlessm.com/T18349
=> Work around automake 1.15+ distcheck

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T18781
=> settings: Hide the weekday in GnomeWallClock by default

Makefile.am, autogen.sh, configure.ac
We need a way to only install the icon theme in order to create a flatpak extension
https://phabricator.endlessm.com/T18342
=> Remove gnome autogen dep and add options to disable things

settings/com.endlessm.settings.gschema.override.in
The reason is that this is only used for showing the welcome dialog at
the moment, and we've decided not to show this dialog as it's not very
useful.
https://phabricator.endlessm.com/T20235
=> settings: Set first-run for GNOME Software as false

debian/eos-icon-theme.conf.in, debian/eos-icon-theme.dirs, debian/eos-icon-theme.install, debian/eos-icon-theme.sh, debian/rules
Use tmpfiles.d to set up folders in /run with symlinks to the EndlessOS
icon theme extension in /var/lib/flatpak and /var/endless-extra/flatpak.
Add profile.d and X11/Xsession.d fragments, similar to flatpak, which
adds the folders to XDG_DATA_DIRS if the icon theme exists (depending
on whether the system is "split" and has its flatpak installations in
/var/endless-extra).
https://phabricator.endlessm.com/T20599
=> add EndlessOS icon theme Flatpak extension to XDG_DATA_DIRS

settings/com.endlessm.settings.gschema.override.in
The California Energy Commission (CEC) requires that computers
enter sleep mode within 30 minutes of user inactivity.
https://phabricator.endlessm.com/T20634
=> settings: default to auto-suspend after 15 minutes

settings/com.endlessm.settings.gschema.override.in
This reverts commit bf77bbf7bd19bfa142be4bad76e1f4c8fc3db71e.
Upstream addressed this issue directly in gnome-settings-daemon,
so we'll go with their patch instead.
Note that the upstream solution went with 20 minutes rather than
15 minutes, matching the European standards (which exceeds the
CEC standard of 30 minutes).
https://phabricator.endlessm.com/T20634
=> Revert "settings: default to auto-suspend after 15 minutes"

settings/com.endlessm.settings.gschema.override.in
Default order is now as follows:
- Internet (hard-coded in shell)
- Settings (hard-coded in shell)
- App Center (added via this commit)
- Calculator (added via this commit)
- Encyclopedias (previously prioritized in this gsetting)
- Weather (added via this commit)
- Help Center (added via this commit)
- All other apps (following any further logic in the shell)
https://phabricator.endlessm.com/T15929
=> settings: prioritize a few more apps in search results

settings/com.endlessm.settings.gschema.override.in
document-font references non-existent "Lato Pro" font.
https://phabricator.endlessm.com/T20961
=> settings: fix typo in gsettings schema

settings/com.endlessm.settings.gschema.override.in
This is used for opening the App Center when a USB with an ostree repo
is inserted.
https://phabricator.endlessm.com/T16950
=> settings: Autorun the app associated with the x-content/ostree-software

settings/com.endlessm.settings.gschema.override.in
This setting is used to display the first run dialog in GNOME Software
(i.e. the shopping bag), but this dialog has now been completely removed
downstream (T21725). So this setting doesn't need to be overridden
anymore.
GNOME Software still sets the first-run dialog to FALSE after its first
launch, so by removing this override, we gain the real information of
whether the program has been run before, which can be interesting in the
future if we decide to show a different first-run dialog.
https://phabricator.endlessm.com/T21725
=> settings: Do not override GNOME Software's first-run setting

settings/com.endlessm.settings.gschema.override.in
This setting is ignored in GNOME Software after T22389 (we always
want to refresh even on metered connections).
https://phabricator.endlessm.com/T22389
=> settings: Remove GNOME Software's refresh-when-metered override

settings/com.endlessm.settings.gschema.override.in
This setting is now ignored in GNOME Software.
https://phabricator.endlessm.com/T22404
=> settings: Remove the "download-updates" GNOME Software setting

settings/com.endlessm.settings.gschema.override.in
Upstream GNOME has gone to click-method=fingers and after trying for a month in
Endless, we have concluded this makes anyone with prior Windows or PC
experience conclude their touchpad is broken, and try to return their computer,
post on the forum, stop using Endless, fail OEM tests, etc. We think it's the
wrong call considering Endless is unlikely to enter the same channels /
geographies as Macs, Chromebooks or super high-end Ultrabooks.
https://phabricator.endlessm.com/T25142
=> settings: set touchpad click-method=default

settings/com.endlessm.settings.gschema.override.in
This will be handled directly in the SDK.
https://phabricator.endlessm.com/T23254
=> settings: Remove Ctrl+Q default for app closing

Makefile.am
For compatibility with deb-build-snapshot, which runs git clean -fdx on the
source tree, dh_autoreconf is configured to run autogen.sh so that the intltool
files are re-created. However, autogen.sh is not included in dist tarballs,
making builds fail on OBS. Ship it to square this circle.
https://phabricator.endlessm.com/T23464
=> Add autogen.sh to EXTRA_DIST

configure.ac
Only fail if we are building settings.
https://phabricator.endlessm.com/T27031
=> configure: make --with-systemdunitdir failure conditional

debian/control
This has been unneeded since b5f3aec7ccf97b54ad030fb17af51317041933b1.
While not logically part of the changes on https://github.com/endlessm/eos-theme/pull/328, I noticed this at the same time.
https://phabricator.endlessm.com/T27255
=> control: remove build-dep on libgtk2.0-bin

settings/com.endlessm.settings.gschema.override.in
This used to be done in GNOME Shell itself, but it's
better to move this override to here.
https://phabricator.endlessm.com/T25835
=> settings: Add Endless-specific default taskbar icons

settings/com.endlessm.settings.gschema.override.in
Superseeds https://github.com/endlessm/eos-theme/pull/324 which had to be reverted while g-s-d is not integrated.
https://phabricator.endlessm.com/T27676
=> settings: Update type for logout in media keys

settings/com.endlessm.settings.gschema.override.in
This MIME type was renamed in the process of being upstreamed; see
https://gitlab.freedesktop.org/xdg/shared-mime-info/merge_requests/22
Update it here so that upon insertion of USB drives containing OS/App
updates, GNOME Software will be automatically opened and the USB
category will be properly populated with apps.
https://phabricator.endlessm.com/T23512
=> settings: Update MIME type for ostree repos

settings/com.endlessm.settings.gschema.override.in
We are moving this setting to gsettings-desktop-schemas so that
gnome-initial-setup can use it without a hard dependency on
gnome-control-center.
Squash with 73e0f7d8abe6c7011d685e1200a52edeaeaee03e on the next rebase.
https://phabricator.endlessm.com/T28364
=> overrides: Get facesdirs setting from gsettings-desktop-schemas

Makefile.am, configure.ac
Building eos-theme for the org.freedesktop.Platform.Icontheme.EndlessOS
flatpak runtime fails because /usr/share/runtime/share/pixmaps is
read-only.
Allow disabling installation of the faces icons. They're only relevant
for the host OS and need not be part of an icon theme runtime.
https://phabricator.endlessm.com/T28493
=> build: Add option to disable faces installation

settings/com.endlessm.settings.gschema.override.in
We have found in practice that the physical orientation of the
accelerometer within the computer hardware is often incorrectly
detected. While we have been able to improve some cases by adding
hardware-specific special cases, this issue still bites users from time
to time, and it is rather hard to recover from – you need to rotate the
laptop to an awkward angle (to convince it to rotate the screen to the
normal landscape orientation) then either click a menu item or press
Win+O, neither of which is easy to do one-handed.
Since we do not specifically aim to support tablets (or convertibles in
tablet mode), disable automatic rotation by default. Brave users can
always enable it using the menu item.
See
https://lists.freedesktop.org/archives/systemd-devel/2019-September/043404.html
and …
=> overrides: disable touchscreen autorotation

settings/com.endlessm.settings.gschema.override.in
This was disabled by default in 2a21c39dc2a7598c589337c603049eb85281e248.
The rationale given was:
> We want our global search to feel more like google where you search
> for things like "Mexico", "rabbit" and what not, and less like a
> traditional system search where you look for "my-list.txt".
I think I understand the sentiment here, but I think the cost (making it 
harder to discover your files) is too high. The lack of local file search
was reported as a bug/feature request by two people within Endless, and I
think that as our target audience has moved further from
“inexperienced, mostly-offline computer user” the need for this feature has
increased somewhat.
Remove it from the 'disabled' list, but leave it naturally sorted within 
the other search provides not listed in the …
=> settings: re-enable Nautilus search provider by default

settings/dconf-defaults/locks/00_settings, settings/dconf-defaults/settings
This introduces a new directory `settings/dconf-defaults/locks` which is responsible for locking the dconf keys. I didn't find any new changes to the makefiles as essentially `dconf compile` takes a entire directory to compile the key-files into the binary-database. I assume the `settings/dconf-defaults/locks`  will also get respected while compilation (Tested locally :heavy_check_mark: )
_________
CC @GeorgesStavracas 
https://phabricator.endlessm.com/T28777
=> Add default dconf value for shell's enabled-extensions and lock them

settings/com.endlessm.settings.gschema.override.in
The `show-folder-management` setting was removed in gnome-software
commit 67a5bff938dad for 3.36.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T28771
=> settings: Remove outdated override for gnome-software

settings/Makefile.am, settings/com.endlessm.EknServicesMultiplexer-flatpak-permissions.desktop
Flatpak (correctly) warns the user about EKN multiplexer continuing to
run as a background process. As the multiplexer is designed to do that,
set the permissions in the xdg-desktop-portal database so that the
multiplexer is allowed to run in the background, and the user isn’t
notified about it.
It has to be done on startup so all users have the permissions set in
their session (xdg-desktop-portal provides no system-wide configuration
hook), and it can’t be done from within Hack as that would require
breaking the flatpak sandboxing.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T29677
=> autostart: Add autostart desktop file to set EKN flatpak permissions

debian/changelog, debian/eos-default-settings.install
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T29677
=> eos-default-settings: Install autostart file for flatpak permissions

safe-defaults/tmpfiles-disable.conf.in, safe-defaults/tmpfiles-enable.conf.in
This was previously only tested with Chrome and so nobody noticed we
had the Chromium config path wrong. We use /etc/chromium-browser so
change any mention of /etc/chromium to this, and remove any noise that
we may have created.
https://phabricator.endlessm.com/T29779
=> safe-defaults: correct Chromium config path to /etc/chromium-browser

settings/com.endlessm.settings.gschema.override.in
Flatpak rewrites apps' search providers to be disabled by default, to
avoid users' desktop searches unwittingly being sent to apps. (Users are
unlikely to expect that installing an app allows it to read all their
searches.)
We trust Learning Equality; so, enable Kolibri's search provider by
default.
This change will only take effect for users who have not manually
enabled any search providers in the past, since it is only a default
value for the key.
https://phabricator.endlessm.com/T28681
=> settings: Enable Kolibri search provider by default

settings/com.endlessm.settings.gschema.override.in
This reverts commit 8a82d272daa4a789cd591d3c84c2f6406c316d2f.
The sample media isn't considered relevant anymore. Maintaining the
infrastructure is costly and a burden. We removed the media and there's
nothing to index.
https://phabricator.endlessm.com/T30533
=> Revert "Let tracker index Endless sample media content"

debian/control
This is needed to ensure the SVG pixbuf loader is installed. Without it,
gtk-encode-symbolic-svg fails to load the source SVG icons. Possibly
libgtk-3-bin should have a harder dependency on librsvg2-common.
Apparently this was pulled in implicitly before by adwaita-icon-theme,
but that's no longer the case.
https://phabricator.endlessm.com/T30533
=> control: Add build depencency on librsvg2-common

settings/com.endlessm.settings.gschema.override.in
This reverts f0148f0f09e113f6ef6862d6894d035122bd41af and
fe2a78d8bc80a13b85dad4183f2b1a7bf53ec760.
In the intervening 7 years, several things have changed:
- We are no longer attempting to run with 1 GB of RAM.
- We have discontinued updates for EC-100.
- We have re-enabled user display server, and GDM's greeter session
self-destructs when not in use.
On multi-user systems, with these features disabled if one user puts
the computer to sleep without logging out, then the computer cannot be
used by another user without forcibly power-cycling the computer. This
has been reported as an issue by at least one deployment, as well as
several individuals within Endless.
https://phabricator.endlessm.com/T14074
=> Re-enable switch user option on user menu and lock screen

debian/control, debian/eos-default-settings.install
Source changes at https://github.com/endlessm/eos-theme/pull/354.
https://phabricator.endlessm.com/T31300
=> eos-default-settings: Ship default container registries configuration

settings/com.endlessm.settings.gschema.override.in
We are going to direct users to rhythmbox's flatpak from flathub and these settings no longer apply.
https://phabricator.endlessm.com/T31426
=> settings: Remove rhythmbox custom settings

icons/index.theme.in
This fixes the following warning:
``` 
(org.gnome.Nautilus:17236): Gtk-WARNING **: 10:06:44.268: Theme file for EndlessOS has no name
``` 
Regression from commit 2763837b3ecab604085f8375eba8490cfed42f10.
https://phabricator.endlessm.com/T31501
=> icons: Fix icon theme name/comment

settings/Makefile.am, settings/com.endlessm.Config.Printing.rules
Install com.endlessm.Config.Printing.rules into
/usr/share/polkit-1/rules.d/. That permits users in group lpadmin to
admin printers via GUI.
https://phabricator.endlessm.com/T30973
=> Install new polkit rule to permit user admin printers

debian/eos-default-settings.install
Install com.endlessm.Config.Printing.rules into
/usr/share/polkit-1/rules.d/.
https://phabricator.endlessm.com/T30973
=> eos-default-settings: Install new polkit rule to permit user admin printers

settings/com.endlessm.Config.Printing.rules
Fix the action ID "org.opensuse.cupspkhelper.mechanism." match
condition.
https://phabricator.endlessm.com/T30973
=> eos-default-settings: Fix cupspkhelper's action ID match condition

debian/eos-default-settings.install
Add the OS NetworkManager conf.d directory. Currently this provides
connectivity check settings for Endless.
https://phabricator.endlessm.com/T32335
=> eos-default-settings: Install NetworkManager conf files

safe-defaults/eos-safe-defaults.service.in
This unit is intended to be run after an OS update, in case the set of
symlinks to install has changed as part of the update. (This was the
case in 4.0.1, and in particular involves deleting a symlink in the
NetworkManager configuration that points to a now-deleted file on disk.)
Unfortunately, the unit was not correctly configured to run before
systemd-update-done.service. This means that ConditionNeedsUpdate=/etc
will never be true when systemd considers activating the unit, so it did
not get run by the OS update. As a result, NetworkManager fails to start
and the computer cannot connect to the internet any more.
Fix this by cargo-culting the relevant systemd dependencies. The key
point is to disable default dependencies, then order this service
between the filesystem becoming available …
=> safe-defaults: Correctly start service after OS update

safe-defaults/dns-over-https.json
Set DnsOverHttpsMode as automatic mode for those types which cannot be
parsed by DNS-over-HTTPS mechanism in Chrome/Chromium.
The "automatic" mode will send DNS-over-HTTPS queries first if a
DNS-over-HTTPS server is available and may fallback to sending insecure
queries on error. [1]
[1]: https://chromeenterprise.google/policies/#DnsOverHttpsMode
https://phabricator.endlessm.com/T32832
=> safe-defaults: DoH: set DnsOverHttpsMode as automatic mode

safe-defaults/eos-safe-defaults.service.in
The original eos-safe-defaults.service will be guarded by "/etc"'s
needing update condition, which leads the service start failed at next
and following boots. Then, Chromium's safe search configration files
will not be linked to Chromium flatpak Policy path which is under
"/run". Because, "/run" is a tmpfs that means safe defaults having no
effect for Chromium after a reboot.
This patch removes the condition check to ensure
eos-safe-defaults.service can start correctly everytime. Also, adds the
stop command to disable safe defaults by systemd control.
https://phabricator.endlessm.com/T32833
=> safe-defaults: Manage safe defaults' state by systemd

settings/com.endlessm.settings.gschema.override.in
Previously we disabled workspaces by:
1. Disabling dynamic workspaces
2. Setting the number of workspaces to '1'
The improved workspace UI was one of the key things validated by the
user research that led up to GNOME 40, and our desktop is now better
aligned with this. Re-enable GNOME's default dynamic workspaces
behaviour.
(GNOME Settings 41 introduced user-facing controls for these settings
anyway.)
I also noticed a couple of other obsolete settings overrides, which this PR removes.
https://phabricator.endlessm.com/T33334
=> settings: Re-enable dynamic workspaces (+2)

settings/com.endlessm.settings.gschema.override.in
x-content/ostree-repository is the type of removable devices which
contain a non-empty directory at the root named .ostree, ostree/repo or
var/lib/flatpak/repo.
In Endless OS 4 and earlier, GNOME Software could install apps and OS
updates from such drives, as a downstream change. This support was
removed to ease the rebase to GNOME Software 41, in hopes of restoring
it upstream later. As a result, inserting a USB drive with such a
directory would cause Software to start and display the following error:
> Failed to install file: not supported
Remove this mime type from the list to autostart.
For reference, the upstream value is:
[ 'x-content/unix-software', 'x-content/ostree-repository' ]
x-content/unix-software is to support the [Desktop Application Autostart
Spec][0] and is handled by …
=> settings: Don't autostart OSTree repos on removable storage

settings/com.endlessm.settings.gschema.override.in
It was removed upstream in commit a695e19504dcf in 2021.
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
https://phabricator.endlessm.com/T33424
=> settings: Drop show-nonfree-prompt GSettings key for gnome-software

settings/com.endlessm.settings.gschema.override.in
This setting was moved in GNOME 40.
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/8c4bca1d2d1a641ccb1a8111b1bc90806d7c144e
'slight' has been the default in GNOME since 2015
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/e2926353e471955e8e684264e826da5b8643e83e
so just drop the override.
https://phabricator.endlessm.com/T33865
=> Remove font hinting override

safe-defaults/eos-safe-defaults.service.in
Both of these units run `update-ca-certificates`, and that script makes no attempt to prevent concurrent execution.
https://phabricator.endlessm.com/T34308
=> safe-defaults: Start unit after eos-update-system-ca.service

safe-defaults/eos-safe-defaults.service.in
Both of these units run `update-ca-certificates`, and that script makes no attempt to prevent concurrent execution.
https://phabricator.endlessm.com/T34308
(cherry picked from commit 2f0aa230d1f059fd3645aefe83b1efd2818684cf)
=> Backport "safe-defaults: Start unit after eos-update-system-ca.service" to eos4.0

settings/com.endlessm.settings.gschema.override.in
A nicer appstream.endlessos.org CNAME is being connected to the CloudFront CDN. Use that instead of the direct distribution domain name.
This depends on https://github.com/endlessm/eos-administration/pull/1303 being deployed.
https://phabricator.endlessm.com/T28855
=> settings: Use new appstream CNAME

gnome-software/Makefile.am, gnome-software/gnome-software-cache.conf
At a minimum this will reclaim some disk space from unused files. Potentially it will remove conflicting entries if current eos-extra appstream catalog has different data than one of the legacy files.
https://phabricator.endlessm.com/T34337
=> gnome-software: Cleanup old eos-extra appstream downloads

debian/eos-default-settings.install, debian/eos-icon-theme.dirs
Actually install the `gnome-software-cache.conf` tmpfiles configuration.
https://phabricator.endlessm.com/T34337
=> tmpfiles packaging

settings/com.endlessm.settings.gschema.override.in
I noticed there is an old override to disable overlay scrollbars, but this is just a GSetting now for GTK4 apps, at least.
=> GSchema: disable overlay scrollbars

settings/com.endlessm.settings.gschema.override.in
This reverts commit c81b7d98fe1c3da35809a05d334bcf716ab384ab.
The [original request] was from over a decade ago, and we have effectively an entirely new Files experience since then, especially as we look to rebase on an even newer GNOME with the GTK4 port of Files.
Let's inherit the upstream defaults here; if we discover a usability issue from the field, we should bring that feedback upstream to GNOME since we're involved with the design team there.
[original request]: https://github.com/endlessm/eos-shell/issues/331
=> Revert "Set default Nautilus view to list view"

settings/com.endlessm.settings.gschema.override.in
This property was removed in GNOME 42 when screencasting was moved to
the shell's new popover. The new implementation has no maximum length.
=> settings: Don't override max-screencast-length

settings/com.endlessm.settings.gschema.override.in
This reverts commit ffcedd7efff2ab7a14e62849532c8ab8421c2548.
Similar to #388, the [original request] was from over a decade ago and looks to be working around a very specific hardware issue combined with the design of EOS at the time. Hardware has improved, it's possible drag detection has improved, and the app grid is completely different these days as well.
This setting doesn't even exist here, either, so I believe it's been a no-op for at least EOS5. 😄 There's `org.gnome.desktop.peripherals.mouse drag-threshold` but I haven't dug in to ensure it's the same thing.
Let's just inherit the upstream defaults here; if we discover a usability issue from the field, we should bring that feedback upstream to GNOME since we're involved with the design team there.
[original request]: …
=> Revert "Decrease the likelihood that an unsteady click is interpreted as a drag"

debian/eos-default-settings.install, icons/Makefile.am, settings/Makefile.am, settings/settings.ini
Previously, we manually enabled this setting in our fork of
gnome-initial-setup. This requires maintaining a downstream patch
forever and also means the setting is not used by other password entries
in the OS, such as in Settings.
Instead, set this globally for GTK 3 and GTK 4.
This PR also includes a build fix which I have been working around (but which was easy to fix once I tried).
https://phabricator.endlessm.com/T27358
=> settings: Show last typed char in GTK password entries

Makefile.am, configure.ac, gnome-initial-setup/Makefile.am, gnome-initial-setup/eos-migrate-gnome-initial-setup-vendor-conf.service, gnome-initial-setup/vendor.conf
This file is moved from eos-image-builder. The copy there also
contained:
[pages]
run_welcome_tour=false
but this key has not been read by Initial Setup for many years.
Rather than shipping this default list of languages as a mutable
customisation in every image, we will now ship the defaults in the
immutable OS and only override it if necessary for a particular image.
----
Although unlikely, it is possible that Initial Setup will run after the
OS has been updated:
- Perhaps the computer goes online during Initial Setup, the automatic
updater runs, and then the user restarts without completing Initial
Setup.
- Perhaps eos-factory-reset is used to remove all users.
Unlikely, but it is easy enough to preserve any vendor overrides in this
case. We can remove this unit in the next checkpoint …
=> Install & migrate gnome-initial-setup vendor.conf file

settings/com.endlessm.settings.gschema.override.in
Currently just setting it to the normal wallpaper, to avoid getting an adwaita-dark wallpaper on eos5.2.
https://phabricator.endlessm.com/T35128
=> settings: Override dark wallpaper

gnome-initial-setup/eos-migrate-gnome-initial-setup-vendor-conf.service
There is no reason why /etc/gnome-initial-setup would exist: the
defaults are shipped in /usr. Create the directory as needed to migrate
any existing overrides.
Fixes 9bc9888753d4e483ac5231fc62a824d8855d70fa
https://phabricator.endlessm.com/T35040
=> gnome-initial-setup: Create directory when migrating vendor.conf

settings/com.endlessm.settings.gschema.override.in
This reverts commit 887b2d644a510a803363f0c01d0be0c79535bd82.
This was added to pass a certification process for use in China, but
this is no longer relevant and we are no longer installing GEdit by
default.
https://phabricator.endlessm.com/T13540
https://phabricator.endlessm.com/T32962
=> Revert "settings: enable GB18030 Chinese encoding by default in gedit"
