backgrounds/Makefile.am
=> Don't install default background links

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T13159
=> gnome-software: Override non-free software options

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T12997
=> settings: remove default limit for screencast length

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T12454
=> settings: Make gnome-software download the eos-extra AppStream file

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T13726
=> settings: Make GNOME Software auto-refresh when on a metered connection

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T13540
=> settings: enable GB18030 Chinese encoding by default in gedit

settings/com.endlessm.settings.gschema.override.in
Since we present the Force Quit dialog on Endless.
https://phabricator.endlessm.com/T13650
=> settings: disable Ctrl+Alt+Delete keybinding for the logout dialog

settings/com.endlessm.settings.gschema.override.in
Instead of only doing it if they're older than a certain age.
https://phabricator.endlessm.com/T13859
=> Always check for new screenshots' versions

debian/eos-default-settings.install
https://phabricator.endlessm.com/T15704
=> add /usr/share/dconf to eos-default-settings package

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T19319
=> settings: Make gnome-software install the external appstream system-wide

debian/copyright, debian/eos-extra-fonts.install
https://phabricator.endlessm.com/T19481
=> Fix license attribution for imported fonts

debian/changelog, debian/eos-default-settings.install
https://phabricator.endlessm.com/T20990
=> T20990 Hide power notifications from t he lock screen by default (Debian changes)

settings/com.endlessm.settings.gschema.override.in
This is a follow-up to commit 342a12a9ab4dcf7dbe3774065302b0159d1185b0.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T25142
=> settings: Fix quoting in GSettings override file

debian/control, debian/eos-default-settings.install, debian/rules
Avoid the automatic starting/enabling of the startup job.
https://phabricator.endlessm.com/T23464
=> Ship eos-safe-defaults in eos-default-settings package

debian/eos-default-settings.install
https://phabricator.endlessm.com/T23464
=> Add missing eos-safe-defaults script

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T27326
=> T27326 Fix gnome-software settings overrides for rebase

debian/control, debian/eos-extra-faces.install
https://phabricator.endlessm.com/T27788
=> Build eos-extra-faces bin package for avatar faces

settings/Makefile.am
Fallout from 9e50a3ca9ec.
https://phabricator.endlessm.com/T28777
=> settings: Include lock files in Makefiles

settings/com.endlessm.settings.gschema.override.in
This is the new, upstreamed key name for this setting.
https://phabricator.endlessm.com/T29718
=> settings: Use 'avatar-directories' instead of 'facesdirs'

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T30734
=> settings: Add clubhouse to default taskbar icons

configure.ac, safe-defaults/Makefile.am, safe-defaults/tmpfiles-disable.conf.in, safe-defaults/tmpfiles-enable.conf.in, settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T30997
=> settings: Use Chromium's Flatpak from flathub when configuring favorites

debian/eos-icon-theme.install
Signed-off-by: Philip Withnall <pwithnall@endlessos.org>
https://phabricator.endlessm.com/T33015
=> debian: Install upgrade banner background for gnome-software

settings/com.endlessm.settings.gschema.override.in
https://phabricator.endlessm.com/T35094
=> Enable Endless Key search provider by default
